export const products = [
  {
    id: 1,
    image: "/placeholder.svg",
    name: "Organic Whole Milk",
    description: "Fresh, creamy whole milk from local farms",
    price: 4.99,
  },
  {
    id: 2,
    image: "/placeholder.svg",
    name: "Artisanal Goat Cheese",
    description: "Handcrafted goat cheese with a unique flavor",
    price: 7.99,
  },
  {
    id: 3,
    image: "/placeholder.svg",
    name: "Probiotic Yogurt",
    description: "Gut-friendly yogurt with live active cultures",
    price: 3.49,
  },
  {
    id: 4,
    image: "/placeholder.svg",
    name: "Grass-Fed Butter",
    description: "Rich, creamy butter from pasture-raised cows",
    price: 5.99,
  },
  {
    id: 5,
    image: "/placeholder.svg",
    name: "Aged Cheddar Cheese",
    description: "Sharp, flavorful cheddar with a smooth texture",
    price: 9.99,
  },
  {
    id: 6,
    image: "/placeholder.svg",
    name: "Lactose-Free Milk",
    description: "Milk for those with lactose intolerance",
    price: 4.49,
  },
  {
    id: 7,
    image: "/placeholder.svg",
    name: "Organic Cottage Cheese",
    description: "Creamy cottage cheese made with simple ingredients",
    price: 3.99,
  },
  {
    id: 8,
    image: "/placeholder.svg",
    name: "Artisanal Feta Cheese",
    description: "Tangy, crumbly feta cheese from a local creamery",
    price: 6.99,
  },
  {
    id: 9,
    image: "/placeholder.svg",
    name: "Kefir Smoothie",
    description: "Probiotic-rich kefir blended with fresh fruit",
    price: 3.79,
  },
  {
    id: 10,
    image: "/placeholder.svg",
    name: "Organic Sour Cream",
    description: "Rich, creamy sour cream made from grass-fed cows",
    price: 4.29,
  },
];
